/* compression_lut.h -- GENERATED by gen_compression_lut.py. DO NOT EDIT. */
/* Half (magnitude) logarithmic-compression LUT, MU=255, 129 int16_t
 * entries at spacing 256 (index = |x| >> 8). Compress() applies the
 * sign and linearly interpolates between adjacent entries. */

#ifndef GLX_COMPRESSION_LUT_H
#define GLX_COMPRESSION_LUT_H

#include <stdint.h>

#define GLX_COMPRESSION_LUT_SIZE 129
#define GLX_COMPRESSION_LUT_STEP 256  /* input codes per entry */

static const int16_t glx_compression_lut[GLX_COMPRESSION_LUT_SIZE] = {
         0,   6476,   9492,  11479,  12963,  14148,  15135,  15981,
     16720,  17377,  17968,  18506,  18998,  19453,  19875,  20269,
     20639,  20986,  21315,  21626,  21921,  22203,  22471,  22728,
     22974,  23211,  23438,  23657,  23868,  24072,  24269,  24459,
     24644,  24823,  24997,  25166,  25330,  25490,  25645,  25797,
     25944,  26089,  26229,  26367,  26501,  26632,  26761,  26886,
     27010,  27130,  27248,  27364,  27478,  27589,  27699,  27806,
     27912,  28015,  28117,  28217,  28316,  28413,  28508,  28602,
     28694,  28785,  28875,  28963,  29050,  29135,  29220,  29303,
     29385,  29466,  29546,  29625,  29702,  29779,  29855,  29930,
     30004,  30076,  30149,  30220,  30290,  30360,  30428,  30496,
     30563,  30630,  30695,  30760,  30825,  30888,  30951,  31013,
     31075,  31136,  31196,  31256,  31315,  31373,  31431,  31489,
     31545,  31602,  31657,  31713,  31767,  31822,  31875,  31928,
     31981,  32034,  32085,  32137,  32188,  32238,  32288,  32338,
     32387,  32436,  32484,  32532,  32580,  32627,  32674,  32721,
     32767,
};

#endif /* GLX_COMPRESSION_LUT_H */
