/* crc_lut.h -- GENERATED by gen_crc_lut.py. DO NOT EDIT. */
/* CRC-32 nibble table: the result of 4 bitwise steps for each of the
 * 16 nibble values, polynomial 0xEDB88320 (reflected ISO-HDLC/zlib).
 * 16 entries x 4 B = 64 B of .rodata, replacing a 1024 B .bss table.
 * CRC-32("123456789") == 0xCBF43926 is checked by the generator. */

#ifndef GLX_CRC_LUT_H
#define GLX_CRC_LUT_H

#include <stdint.h>

#define GLX_CRC_NIBBLE_BITS 4
#define GLX_CRC_LUT_SIZE    16  /* 1 << GLX_CRC_NIBBLE_BITS */

static const uint32_t glx_crc32_nibble_lut[GLX_CRC_LUT_SIZE] = {
    0x00000000u, 0x1DB71064u, 0x3B6E20C8u, 0x26D930ACu,
    0x76DC4190u, 0x6B6B51F4u, 0x4DB26158u, 0x5005713Cu,
    0xEDB88320u, 0xF00F9344u, 0xD6D6A3E8u, 0xCB61B38Cu,
    0x9B64C2B0u, 0x86D3D2D4u, 0xA00AE278u, 0xBDBDF21Cu,
};

#endif /* GLX_CRC_LUT_H */
