#!/usr/bin/env python3
# gen_crc_lut.py
# ----------------------------------------------------------------------------
# Bake the CRC-32 nibble table into crc_lut.h (a static const C array), the same
# way gen_compression_lut.py / gen_resample_taps.py / gen_huffman_lut.py bake
# their tables. The CRC table used to be the odd one out: built at runtime into
# 1 KB of .bss on first use. It is a pure function of the polynomial, so it is a
# compile-time constant like every other table here, and on a small target RAM
# is the scarce resource while flash is not.
#
# NIBBLE, NOT BYTE. A table-driven CRC consumes n bits per lookup and costs 2^n
# entries: 8 bits -> 256 entries (1024 B), 4 bits -> 16 entries (64 B). GLX
# checksums only the Huffman payload, a few KB per second of audio, so the
# 256-entry table is sized for a throughput this codec will never see. The
# nibble table is 1/16 the size, costs one extra lookup per byte, and is small
# enough to stay resident in cache on a small core.
#
# The emitted values are bit-identical to the byte table's results -- same
# polynomial, same reflected convention -- so the container format is unchanged
# and existing .glx files still validate.
#
# Run:  python3 gen_crc_lut.py   (writes crc_lut.h)
# ----------------------------------------------------------------------------

import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_PATH = os.path.join(HERE, "crc_lut.h")

POLY = 0xEDB88320  # reflected CRC-32 (ISO-HDLC / zlib), matches crc.c
NIBBLE_BITS = 4
NENTRIES = 1 << NIBBLE_BITS

# Known-answer test: the standard CRC-32 check value for the ASCII string
# "123456789". Verified here so a broken generator cannot emit a plausible but
# wrong table.
KAT_INPUT = b"123456789"
KAT_EXPECT = 0xCBF43926


def build_table():
    """Result of running NIBBLE_BITS bitwise CRC steps on each nibble value."""
    table = []
    for i in range(NENTRIES):
        c = i
        for _ in range(NIBBLE_BITS):
            c = (POLY ^ (c >> 1)) if (c & 1) else (c >> 1)
        table.append(c)
    return table


def crc32_nibble(data, table):
    """The exact algorithm crc.c will run, used to check the table."""
    crc = 0xFFFFFFFF
    for b in data:
        crc ^= b
        crc = (crc >> 4) ^ table[crc & 0x0F]
        crc = (crc >> 4) ^ table[crc & 0x0F]
    return crc ^ 0xFFFFFFFF


def main():
    table = build_table()

    got = crc32_nibble(KAT_INPUT, table)
    if got != KAT_EXPECT:
        raise SystemExit("known-answer test failed: got %08X, expected %08X"
                         % (got, KAT_EXPECT))

    lines = []
    lines.append("/* crc_lut.h -- GENERATED by gen_crc_lut.py. DO NOT EDIT. */")
    lines.append("/* CRC-32 nibble table: the result of %d bitwise steps for each of the"
                 % NIBBLE_BITS)
    lines.append(" * %d nibble values, polynomial 0x%08X (reflected ISO-HDLC/zlib)." % (NENTRIES, POLY))
    lines.append(" * %d entries x 4 B = %d B of .rodata, replacing a %d B .bss table."
                 % (NENTRIES, NENTRIES * 4, 256 * 4))
    lines.append(" * CRC-32(\"123456789\") == 0x%08X is checked by the generator. */" % KAT_EXPECT)
    lines.append("")
    lines.append("#ifndef GLX_CRC_LUT_H")
    lines.append("#define GLX_CRC_LUT_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("#define GLX_CRC_NIBBLE_BITS %d" % NIBBLE_BITS)
    lines.append("#define GLX_CRC_LUT_SIZE    %d  /* 1 << GLX_CRC_NIBBLE_BITS */" % NENTRIES)
    lines.append("")
    lines.append("static const uint32_t glx_crc32_nibble_lut[GLX_CRC_LUT_SIZE] = {")
    for row in range(0, NENTRIES, 4):
        chunk = ", ".join("0x%08Xu" % v for v in table[row:row + 4])
        lines.append("    %s," % chunk)
    lines.append("};")
    lines.append("")
    lines.append("#endif /* GLX_CRC_LUT_H */")

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s (%d entries, %d bytes)" % (OUT_PATH, NENTRIES, NENTRIES * 4))


if __name__ == "__main__":
    main()
