#!/usr/bin/env python3
# gen_compression_lut.py
# ----------------------------------------------------------------------------
# Generate the fixed logarithmic-compression LUT used by the GLX encoder's
# Compress() step. The LUT is a COMPILE-TIME parameter: it is baked into
# compression_lut.h and shipped in the binary. It is NEVER placed in the
# bitstream -- the decoder side does not even need it (the decoder follows the
# pseudocode literally and skips the inverse expand), but the table is a fixed,
# shared constant so the encoder is fully reproducible.
#
# The compression curve is a logarithmic (mu-law-shaped) companding law:
#
#     y_norm = sign(x_norm) * log(1 + MU*|x_norm|) / log(1 + MU)
#
# Because the curve is ODD-SYMMETRIC we only store the positive half (the
# magnitude curve). Compress() in compression.c re-applies the sign at runtime.
#
# Sampling: the runtime uses `index = |x| >> 8`, i.e. one table entry every 256
# input codes. Over the 16-bit magnitude range [0, 32768] that is 128 steps, so
# we emit 129 entries (indices 0..128) -- entry 128 (=32768) is the guard point
# that Compress()'s interpolation reads as LUT[index + 1] for the top segment.
# Each entry is an int16_t in [0, 32767].
#
# Run:  python3 gen_compression_lut.py   (writes compression_lut.h next to this)
# ----------------------------------------------------------------------------

import math
import os

MU = 255.0            # compression curve parameter (same MU used across GLX)
STEP = 256            # input codes per table entry (index = |x| >> 8)
N_ENTRIES = 129       # indices 0..128; entry 128 is the top interpolation guard
FULL_SCALE = 32768.0  # |x| normalization divisor
OUT_SCALE = 32767     # compressed magnitude is scaled back up into int16 range


def compressed_magnitude(x_abs):
    """Compressed magnitude for a non-negative input magnitude x_abs."""
    x_norm = x_abs / FULL_SCALE
    y_norm = math.log1p(MU * x_norm) / math.log1p(MU)
    return int(round(y_norm * OUT_SCALE))


def main():
    entries = []
    for i in range(N_ENTRIES):
        x_abs = i * STEP                 # 0, 256, 512, ..., 32768
        y = compressed_magnitude(x_abs)
        if y > 32767:                    # clamp the guard point into int16 range
            y = 32767
        entries.append(y)

    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "compression_lut.h")
    with open(out_path, "w") as f:
        f.write("/* compression_lut.h -- GENERATED by gen_compression_lut.py. DO NOT EDIT. */\n")
        f.write("/* Half (magnitude) logarithmic-compression LUT, MU=255, 129 int16_t\n")
        f.write(" * entries at spacing 256 (index = |x| >> 8). Compress() applies the\n")
        f.write(" * sign and linearly interpolates between adjacent entries. */\n\n")
        f.write("#ifndef GLX_COMPRESSION_LUT_H\n#define GLX_COMPRESSION_LUT_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("#define GLX_COMPRESSION_LUT_SIZE %d\n" % N_ENTRIES)
        f.write("#define GLX_COMPRESSION_LUT_STEP %d  /* input codes per entry */\n\n" % STEP)
        f.write("static const int16_t glx_compression_lut[GLX_COMPRESSION_LUT_SIZE] = {\n")
        for row_start in range(0, N_ENTRIES, 8):
            row = entries[row_start:row_start + 8]
            f.write("    " + ", ".join("%6d" % v for v in row) + ",\n")
        f.write("};\n\n")
        f.write("#endif /* GLX_COMPRESSION_LUT_H */\n")

    print("wrote %s (%d entries)" % (out_path, N_ENTRIES))


if __name__ == "__main__":
    main()
