/* huffman_lut.h -- GENERATED by gen_huffman_lut.py. DO NOT EDIT. */
/* Static Huffman code table per bit depth, baked from
 * huffman_tables_10.csv at alpha=0.5 (see gen_huffman_lut.py for why
 * one alpha's table is valid for every alpha). Index by
 * symbol_index = residual + offset. */

#ifndef GLX_HUFFMAN_LUT_H
#define GLX_HUFFMAN_LUT_H

#include <stdint.h>

typedef struct {
    const uint16_t *code;  /* canonical codeword bits, MSB-first */
    const uint8_t  *len;   /* codeword bit length per symbol */
    int nsym;              /* number of symbols in this subtable */
    int offset;            /* symbol_index = residual + offset */
} GlxHuffSubtable;

static const uint16_t glx_huff_code_b1[3] = { 2, 0, 3 };
static const uint8_t  glx_huff_len_b1[3]  = { 2, 1, 2 };
static const uint16_t glx_huff_code_b2[7] = { 47, 22, 3, 0, 4, 10, 46 };
static const uint8_t  glx_huff_len_b2[7]  = { 6, 5, 2, 1, 3, 4, 6 };
static const uint16_t glx_huff_code_b3[15] = { 11263, 11262, 5630, 2814, 86, 11, 4, 0, 3, 20, 42, 174, 1406, 702, 350 };
static const uint8_t  glx_huff_len_b3[15]  = { 14, 14, 13, 12, 7, 4, 3, 1, 2, 5, 6, 8, 11, 10, 9 };

static const GlxHuffSubtable glx_huff_tables[3] = {
    { glx_huff_code_b1, glx_huff_len_b1, 3, 1 },
    { glx_huff_code_b2, glx_huff_len_b2, 7, 3 },
    { glx_huff_code_b3, glx_huff_len_b3, 15, 7 },
};

#endif /* GLX_HUFFMAN_LUT_H */
