#!/usr/bin/env python3
# gen_huffman_lut.py
# ----------------------------------------------------------------------------
# Bake huffman_tables_10.csv into huffman_lut.h (static C arrays). The static
# Huffman code tables are a COMPILE-TIME parameter shared by encoder and
# decoder; only the (bits, seed, sample count) needed to select and reproduce
# a decode ride in the bitstream header -- never the table itself.
#
# ONE TABLE PER BIT DEPTH, NOT PER ALPHA. The residual PMF is unimodal and
# symmetric around 0 for every alpha in [0,1] -- alpha only spreads
# probability mass outward, it never reorders it (residual=0 is always most
# likely, then +-1, then +-2, ...). Huffman code LENGTH is a function of
# probability RANK, not exact value, so the length allocation is invariant to
# alpha; checked empirically against huffman_tables_10.csv, the per-symbol
# length MULTISET is identical across all 11 alphas for every bits value. The
# only thing that ever differs between alphas is which of two near-tied
# symbols (e.g. +-1) gets which of two equal-length codewords -- a coin flip
# between probabilities equal to within simulation noise, so picking any one
# alpha's table and reusing it for every alpha costs nothing: it is still a
# valid, optimal-length prefix code for every alpha, not an approximation.
#
# So: one canonical alpha (CANONICAL_ALPHA below) supplies the (code, length)
# table per bits; alpha only still matters for dither amplitude, not for
# Huffman table selection.
#
# CSV columns: bits, alpha, symbol, probability, code, length
#   - `symbol` is the residual DISPLAY value: residual / 2^(bits-1).
#     The integer residual is  round(symbol * 2^(bits-1)).
#   - `code`   is the literal binary codeword (digits), emitted MSB-first.
#   - `length` is that codeword's bit length.
#
# For a given `bits`, the residual (first-order delta of b-bit quantizer codes)
# ranges over [-(2^bits - 1), +(2^bits - 1)] -> 2^(bits+1)-1 symbols. We index
# the table by  symbol_index = residual + OFFSET,  OFFSET = 2^bits - 1.
#
# Run:  python3 gen_huffman_lut.py   (reads huffman_tables_10.csv, writes header)
# ----------------------------------------------------------------------------

import csv
import os

HERE = os.path.dirname(os.path.abspath(__file__))
# Generated headers live in src/generated/, one level up from tools/.
OUT_DIR = os.path.join(HERE, os.pardir, "src", "generated")
CSV_PATH = os.path.join(HERE, "huffman_tables_10.csv")   # data sits beside this script
OUT_PATH = os.path.join(OUT_DIR, "huffman_lut.h")

CANONICAL_ALPHA = 0.5   # midpoint; any alpha's table would do, see note above
BITS_RANGE = [1, 2, 3]


def main():
    # rows[bits] = list of (residual, code_int, length), from the canonical alpha only
    rows = {}
    with open(CSV_PATH, newline="") as f:
        reader = csv.DictReader(f)
        for r in reader:
            if abs(float(r["alpha"]) - CANONICAL_ALPHA) > 1e-9:
                continue
            bits = int(r["bits"])
            symbol = float(r["symbol"])
            residual = int(round(symbol * (1 << (bits - 1))))
            code_str = r["code"].strip()
            length = int(r["length"])
            code_int = int(code_str, 2) if code_str else 0
            rows.setdefault(bits, []).append((residual, code_int, length))

    lines = []
    lines.append("/* huffman_lut.h -- GENERATED by gen_huffman_lut.py. DO NOT EDIT. */")
    lines.append("/* Static Huffman code table per bit depth, baked from")
    lines.append(" * huffman_tables_10.csv at alpha=%.1f (see gen_huffman_lut.py for why" % CANONICAL_ALPHA)
    lines.append(" * one alpha's table is valid for every alpha). Index by")
    lines.append(" * symbol_index = residual + offset. */")
    lines.append("")
    lines.append("#ifndef GLX_HUFFMAN_LUT_H")
    lines.append("#define GLX_HUFFMAN_LUT_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    const uint16_t *code;  /* canonical codeword bits, MSB-first */")
    lines.append("    const uint8_t  *len;   /* codeword bit length per symbol */")
    lines.append("    int nsym;              /* number of symbols in this subtable */")
    lines.append("    int offset;            /* symbol_index = residual + offset */")
    lines.append("} GlxHuffSubtable;")
    lines.append("")

    # emit one array pair per bit depth
    for bits in BITS_RANGE:
        offset = (1 << bits) - 1
        nsym = (1 << (bits + 1)) - 1
        entries = rows.get(bits)
        if entries is None:
            raise SystemExit("missing CSV rows for bits=%d alpha=%.1f"
                             % (bits, CANONICAL_ALPHA))
        # order by symbol_index so array position == residual + offset
        by_index = [None] * nsym
        for residual, code_int, length in entries:
            idx = residual + offset
            by_index[idx] = (code_int, length)
        if any(e is None for e in by_index):
            raise SystemExit("incomplete table bits=%d alpha=%.1f" % (bits, CANONICAL_ALPHA))
        codes = ", ".join(str(e[0]) for e in by_index)
        lens = ", ".join(str(e[1]) for e in by_index)
        lines.append("static const uint16_t glx_huff_code_b%d[%d] = { %s };"
                     % (bits, nsym, codes))
        lines.append("static const uint8_t  glx_huff_len_b%d[%d]  = { %s };"
                     % (bits, nsym, lens))
    lines.append("")

    # the [bits-1] dispatch table -- one entry per bit depth, no alpha dimension
    lines.append("static const GlxHuffSubtable glx_huff_tables[3] = {")
    for bits in BITS_RANGE:
        offset = (1 << bits) - 1
        nsym = (1 << (bits + 1)) - 1
        lines.append("    { glx_huff_code_b%d, glx_huff_len_b%d, %d, %d },"
                     % (bits, bits, nsym, offset))
    lines.append("};")
    lines.append("")
    lines.append("#endif /* GLX_HUFFMAN_LUT_H */")

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s" % OUT_PATH)


if __name__ == "__main__":
    main()
