#!/usr/bin/env python3
# gen_resample_taps.py
# ----------------------------------------------------------------------------
# Generate the fixed anti-aliasing low-pass FIR used before decimation, per the
# Resample stage in pseudocode.txt:
#
#   PCM (48 kHz) -> AntiAliasFilter -> Decimate(factor=3) -> 16 kHz
#
# A windowed-sinc low-pass, Hamming window, cutoff at the DECIMATED Nyquist
# (8 kHz at a 48 kHz input rate, i.e. normalized fc = 1 / (2 * factor) = 1/6
# cycles/sample) so frequencies above 8 kHz are attenuated before every 3rd
# sample is kept -- this is what prevents aliasing.
#
# Like the compression and Huffman tables, the taps are a COMPILE-TIME fixed
# parameter: baked into resample_taps.h as Q15 int16_t coefficients so the
# runtime FIR stays integer/libm-free. Odd tap count -> exact linear phase
# (symmetric, zero group-delay distortion within the passband).
#
# Run:  python3 gen_resample_taps.py   (writes resample_taps.h next to this)
# ----------------------------------------------------------------------------

import math
import os

NTAPS = 31          # odd -> symmetric, linear phase
IN_RATE = 48000     # every decimation below starts from the 48 kHz input rate

# One tap set per decimation factor actually used by the codebase:
#   3 -> 16 kHz (GLX's own working rate)
#   6 ->  8 kHz (G.711 / G.726 narrowband telephony)
# Each gets its own cutoff at ITS decimated Nyquist; reusing the factor-3
# filter for a factor-6 decimation would leave 4..8 kHz energy in place to
# fold back as aliasing.
FACTORS = [3, 6]


def sinc(x):
    if x == 0.0:
        return 1.0
    px = math.pi * x
    return math.sin(px) / px


def design(factor):
    """Q15 Hamming-windowed-sinc low-pass, cutoff at the decimated Nyquist."""
    fc = 1.0 / (2 * factor)   # normalized cutoff, cycles/sample
    mid = (NTAPS - 1) / 2.0
    taps = []
    for n in range(NTAPS):
        ideal = 2.0 * fc * sinc(2.0 * fc * (n - mid))
        window = 0.54 - 0.46 * math.cos(2.0 * math.pi * n / (NTAPS - 1))  # Hamming
        taps.append(ideal * window)

    # normalize to unity DC gain (sum of taps == 1) before quantizing
    total = sum(taps)
    taps = [t / total for t in taps]

    q15 = [int(round(t * 32768.0)) for t in taps]
    # clamp defensively (a well-formed LPF never approaches full scale per-tap)
    return [max(-32768, min(32767, v)) for v in q15]


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    # Generated headers live in src/generated/, one level up from tools/.
    out_path = os.path.join(here, os.pardir, "src", "generated",
                            "resample_taps.h")
    with open(out_path, "w") as f:
        f.write("/* resample_taps.h -- GENERATED by gen_resample_taps.py. DO NOT EDIT. */\n")
        f.write("/* %d-tap Hamming-windowed-sinc anti-alias low-pass filters, Q15, one per\n"
                " * decimation factor, each cut off at ITS OWN decimated Nyquist.\n"
                " * Unity DC gain (sum ~= 32768 in Q15). Symmetric -> linear phase. */\n\n"
                % NTAPS)
        f.write("#ifndef GLX_RESAMPLE_TAPS_H\n#define GLX_RESAMPLE_TAPS_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("#define GLX_RESAMPLE_TAPS_N %d\n\n" % NTAPS)

        for factor in FACTORS:
            q15 = design(factor)
            fc = 1.0 / (2 * factor)

            # resample.c folds the dot product on tap symmetry and accumulates
            # in int32. Both are only valid for taps that are actually
            # symmetric and whose absolute sum bounds the accumulator, so
            # assert here and export the bound rather than let the C trust a
            # hand-computed number.
            if q15 != q15[::-1]:
                raise SystemExit("factor=%d taps are not symmetric -- "
                                 "resample.c's symmetry folding would be wrong"
                                 % factor)
            abs_sum = sum(abs(v) for v in q15)
            if abs_sum * 32768 >= 2**31:
                raise SystemExit("factor=%d taps overflow an int32 accumulator "
                                 "(sum|taps|=%d)" % (factor, abs_sum))

            f.write("/* factor=%d: %d kHz -> %d kHz, fc=%.6f cycles/sample = %g kHz @ %g kHz */\n"
                    % (factor, IN_RATE // 1000, IN_RATE // factor // 1000, fc,
                       IN_RATE * fc / 1000.0, IN_RATE / 1000.0))
            f.write("static const int16_t glx_resample_taps_f%d[GLX_RESAMPLE_TAPS_N] = {\n"
                    % factor)
            for row_start in range(0, NTAPS, 8):
                row = q15[row_start:row_start + 8]
                f.write("    " + ", ".join("%6d" % v for v in row) + ",\n")
            f.write("};\n")
            f.write("/* sum|taps| -- bounds resample.c's int32 accumulator at\n"
                    " * 32768 * %d = %d, against INT32_MAX 2147483647. */\n"
                    % (abs_sum, abs_sum * 32768))
            f.write("#define GLX_RESAMPLE_TAPSUM_F%d %d\n\n" % (factor, abs_sum))
            print("factor=%d: %d taps, sum=%d, sum|taps|=%d, symmetric"
                  % (factor, NTAPS, sum(q15), abs_sum))

        f.write("#endif /* GLX_RESAMPLE_TAPS_H */\n")

    print("wrote %s" % out_path)


if __name__ == "__main__":
    main()
